MiniGrid-Empty-v0:
  env_type: GymMiniGrid
  # env_size: 62
  # abs_ticks:
  # - [15, 30, 60]
  # - [20, 40, 60]
  # - [30, 45, 60]
  # env_size: 86
  # abs_ticks:
  # - [28, 56, 84]
  env_size: 62
  # abs_ticks:
  #   - [5, 10, 30]
  # - [10, 20, 30]
  #   - [20, 25, 30]
  agent_start_pos: [1, 1]
  total_timesteps: 100000
  init_steps: 3000
  input_format: full_obs
  grd_hidden_dims:
    - 8
    - 16
    - 32
  grd_embedding_dim: 64
  n_clusters: 9
  cluster_embedding_dim: 2
  # lr_ground_Q: 0.0002
  # lr_abstract_V: 0.1
  lr_ground_Q: lin_0.0002
  lr_abstract_V: 0.01
  # lr_encoder: 0.0005
  # lr_decoder: 0.0005
  batch_size: 64
  size_replay_memory: 10000
  gamma: 0.99
  abstract_gamma: 0.99
  omega: 10
  ground_tau: 1
  # abstract_tau: 0.2
  # encoder_tau: 0.2
  exploration_fraction: 1
  exploration_initial_eps: 0.6
  exploration_final_eps: 0.01
  save_model_every: 500000.0
  ground_learn_every: 4
  ground_sync_every: 8
  ground_gradient_steps: 1
  abstract_learn_every: 10000
  abstract_sync_every: 8
  abstract_gradient_steps: 1000
  # learn_with_ae: True
  # init_clustering: True
  use_shaping: False
  # wandb_group: AE_KMeans_DQN
  # wandb_group: AE_DQN
  wandb_group: AdapAbsLazy_noshp_env63_100k_buf10k_alr0.01_shaddow
  # wandb_group: shp_100k_lrabs0.1_tau0.1_aevery4_rrward_mod
  wandb_notes: nothing
  # wandb_tags: ["shp", "omg1", "tbl", "16x16", "(1,1)"]
  clip_grad: True
  # validate_every: 1000
  reset_training_info_every: 1000
  save_recon_every: 1000
  # buffer_recent_states_every: 1000

MiniGrid-FourRooms-v0:
  env_type: GymMiniGrid
  env_size: 19
  agent_start_pos: [1, 1]
  goal_pos: [17, 17]
  input_format: fake_img
  tile_size: 6
  total_timesteps: 30000
  init_steps: 3000
  hidden_dims:
    - 16
    - 32
  embedding_dim: 64
  n_clusters: 4
  cluster_embedding_dim: 8
  # lr_ground_Q: 0.0002
  # lr_abstract_V: 0.1
  lr_ground_Q: lin_0.0002
  lr_abstract_V: 1.0
  # lr_encoder: 0.0005
  # lr_decoder: 0.0005
  batch_size: 256
  size_replay_memory: 50000
  gamma: 0.99
  abstract_gamma: 0.99
  omega: 1
  ground_tau: 0.01
  # abstract_tau: 0.2
  # encoder_tau: 0.2
  exploration_fraction: 1
  exploration_initial_eps: 0.6
  exploration_final_eps: 0.01
  save_model_every: 500000.0
  ground_learn_every: 4
  ground_sync_every: 200
  ground_gradient_steps: 1
  abstract_learn_every: 4
  abstract_sync_every: 8
  abstract_gradient_steps: 1
  # learn_with_ae: True
  # init_clustering: True
  use_shaping: True
  # wandb_group: AE_KMeans_DQN
  # wandb_group: AE_DQN
  wandb_group: AdapAbs_shp_env62_50k_buf10k
  # wandb_group: shp_100k_lrabs0.1_tau0.1_aevery4_rrward_mod
  wandb_notes: shaping not using just updated abs-values
  # wandb_tags: ["shp", "omg1", "tbl", "16x16", "(1,1)"]
  clip_grad: True
  # validate_every: 1000
  reset_training_info_every: 1000
  save_recon_every: 1000
  # buffer_recent_states_every: 1000
